# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drs239/Git-Projs/Minecraft_Cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drs239/Git-Projs/Minecraft_Cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drs239/Git-Projs/Minecraft_Cpp/CMakeFiles /home/drs239/Git-Projs/Minecraft_Cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drs239/Git-Projs/Minecraft_Cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/drs239/Git-Projs/Minecraft_Cpp/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mc_client

# Build rule for target.
mc_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mc_client
.PHONY : mc_client

# fast build rule for target.
mc_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/build
.PHONY : mc_client/fast

src/authenticate/auth_manager.o: src/authenticate/auth_manager.cpp.o
.PHONY : src/authenticate/auth_manager.o

# target to build an object file
src/authenticate/auth_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/authenticate/auth_manager.cpp.o
.PHONY : src/authenticate/auth_manager.cpp.o

src/authenticate/auth_manager.i: src/authenticate/auth_manager.cpp.i
.PHONY : src/authenticate/auth_manager.i

# target to preprocess a source file
src/authenticate/auth_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/authenticate/auth_manager.cpp.i
.PHONY : src/authenticate/auth_manager.cpp.i

src/authenticate/auth_manager.s: src/authenticate/auth_manager.cpp.s
.PHONY : src/authenticate/auth_manager.s

# target to generate assembly for a file
src/authenticate/auth_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/authenticate/auth_manager.cpp.s
.PHONY : src/authenticate/auth_manager.cpp.s

src/buffer/read_buffer.o: src/buffer/read_buffer.cpp.o
.PHONY : src/buffer/read_buffer.o

# target to build an object file
src/buffer/read_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/buffer/read_buffer.cpp.o
.PHONY : src/buffer/read_buffer.cpp.o

src/buffer/read_buffer.i: src/buffer/read_buffer.cpp.i
.PHONY : src/buffer/read_buffer.i

# target to preprocess a source file
src/buffer/read_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/buffer/read_buffer.cpp.i
.PHONY : src/buffer/read_buffer.cpp.i

src/buffer/read_buffer.s: src/buffer/read_buffer.cpp.s
.PHONY : src/buffer/read_buffer.s

# target to generate assembly for a file
src/buffer/read_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/buffer/read_buffer.cpp.s
.PHONY : src/buffer/read_buffer.cpp.s

src/buffer/write_buffer.o: src/buffer/write_buffer.cpp.o
.PHONY : src/buffer/write_buffer.o

# target to build an object file
src/buffer/write_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/buffer/write_buffer.cpp.o
.PHONY : src/buffer/write_buffer.cpp.o

src/buffer/write_buffer.i: src/buffer/write_buffer.cpp.i
.PHONY : src/buffer/write_buffer.i

# target to preprocess a source file
src/buffer/write_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/buffer/write_buffer.cpp.i
.PHONY : src/buffer/write_buffer.cpp.i

src/buffer/write_buffer.s: src/buffer/write_buffer.cpp.s
.PHONY : src/buffer/write_buffer.s

# target to generate assembly for a file
src/buffer/write_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/buffer/write_buffer.cpp.s
.PHONY : src/buffer/write_buffer.cpp.s

src/crypto/aes_cipher.o: src/crypto/aes_cipher.cpp.o
.PHONY : src/crypto/aes_cipher.o

# target to build an object file
src/crypto/aes_cipher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/crypto/aes_cipher.cpp.o
.PHONY : src/crypto/aes_cipher.cpp.o

src/crypto/aes_cipher.i: src/crypto/aes_cipher.cpp.i
.PHONY : src/crypto/aes_cipher.i

# target to preprocess a source file
src/crypto/aes_cipher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/crypto/aes_cipher.cpp.i
.PHONY : src/crypto/aes_cipher.cpp.i

src/crypto/aes_cipher.s: src/crypto/aes_cipher.cpp.s
.PHONY : src/crypto/aes_cipher.s

# target to generate assembly for a file
src/crypto/aes_cipher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/crypto/aes_cipher.cpp.s
.PHONY : src/crypto/aes_cipher.cpp.s

src/crypto/encryption.o: src/crypto/encryption.cpp.o
.PHONY : src/crypto/encryption.o

# target to build an object file
src/crypto/encryption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/crypto/encryption.cpp.o
.PHONY : src/crypto/encryption.cpp.o

src/crypto/encryption.i: src/crypto/encryption.cpp.i
.PHONY : src/crypto/encryption.i

# target to preprocess a source file
src/crypto/encryption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/crypto/encryption.cpp.i
.PHONY : src/crypto/encryption.cpp.i

src/crypto/encryption.s: src/crypto/encryption.cpp.s
.PHONY : src/crypto/encryption.s

# target to generate assembly for a file
src/crypto/encryption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/crypto/encryption.cpp.s
.PHONY : src/crypto/encryption.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/network/http/http_handler.o: src/network/http/http_handler.cpp.o
.PHONY : src/network/http/http_handler.o

# target to build an object file
src/network/http/http_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/http/http_handler.cpp.o
.PHONY : src/network/http/http_handler.cpp.o

src/network/http/http_handler.i: src/network/http/http_handler.cpp.i
.PHONY : src/network/http/http_handler.i

# target to preprocess a source file
src/network/http/http_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/http/http_handler.cpp.i
.PHONY : src/network/http/http_handler.cpp.i

src/network/http/http_handler.s: src/network/http/http_handler.cpp.s
.PHONY : src/network/http/http_handler.s

# target to generate assembly for a file
src/network/http/http_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/http/http_handler.cpp.s
.PHONY : src/network/http/http_handler.cpp.s

src/network/network_manager.o: src/network/network_manager.cpp.o
.PHONY : src/network/network_manager.o

# target to build an object file
src/network/network_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/network_manager.cpp.o
.PHONY : src/network/network_manager.cpp.o

src/network/network_manager.i: src/network/network_manager.cpp.i
.PHONY : src/network/network_manager.i

# target to preprocess a source file
src/network/network_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/network_manager.cpp.i
.PHONY : src/network/network_manager.cpp.i

src/network/network_manager.s: src/network/network_manager.cpp.s
.PHONY : src/network/network_manager.s

# target to generate assembly for a file
src/network/network_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/network_manager.cpp.s
.PHONY : src/network/network_manager.cpp.s

src/network/tcp/tcp_handler.o: src/network/tcp/tcp_handler.cpp.o
.PHONY : src/network/tcp/tcp_handler.o

# target to build an object file
src/network/tcp/tcp_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/tcp/tcp_handler.cpp.o
.PHONY : src/network/tcp/tcp_handler.cpp.o

src/network/tcp/tcp_handler.i: src/network/tcp/tcp_handler.cpp.i
.PHONY : src/network/tcp/tcp_handler.i

# target to preprocess a source file
src/network/tcp/tcp_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/tcp/tcp_handler.cpp.i
.PHONY : src/network/tcp/tcp_handler.cpp.i

src/network/tcp/tcp_handler.s: src/network/tcp/tcp_handler.cpp.s
.PHONY : src/network/tcp/tcp_handler.s

# target to generate assembly for a file
src/network/tcp/tcp_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/network/tcp/tcp_handler.cpp.s
.PHONY : src/network/tcp/tcp_handler.cpp.s

src/util/compression_util.o: src/util/compression_util.cpp.o
.PHONY : src/util/compression_util.o

# target to build an object file
src/util/compression_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/util/compression_util.cpp.o
.PHONY : src/util/compression_util.cpp.o

src/util/compression_util.i: src/util/compression_util.cpp.i
.PHONY : src/util/compression_util.i

# target to preprocess a source file
src/util/compression_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/util/compression_util.cpp.i
.PHONY : src/util/compression_util.cpp.i

src/util/compression_util.s: src/util/compression_util.cpp.s
.PHONY : src/util/compression_util.s

# target to generate assembly for a file
src/util/compression_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mc_client.dir/build.make CMakeFiles/mc_client.dir/src/util/compression_util.cpp.s
.PHONY : src/util/compression_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mc_client"
	@echo "... src/authenticate/auth_manager.o"
	@echo "... src/authenticate/auth_manager.i"
	@echo "... src/authenticate/auth_manager.s"
	@echo "... src/buffer/read_buffer.o"
	@echo "... src/buffer/read_buffer.i"
	@echo "... src/buffer/read_buffer.s"
	@echo "... src/buffer/write_buffer.o"
	@echo "... src/buffer/write_buffer.i"
	@echo "... src/buffer/write_buffer.s"
	@echo "... src/crypto/aes_cipher.o"
	@echo "... src/crypto/aes_cipher.i"
	@echo "... src/crypto/aes_cipher.s"
	@echo "... src/crypto/encryption.o"
	@echo "... src/crypto/encryption.i"
	@echo "... src/crypto/encryption.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network/http/http_handler.o"
	@echo "... src/network/http/http_handler.i"
	@echo "... src/network/http/http_handler.s"
	@echo "... src/network/network_manager.o"
	@echo "... src/network/network_manager.i"
	@echo "... src/network/network_manager.s"
	@echo "... src/network/tcp/tcp_handler.o"
	@echo "... src/network/tcp/tcp_handler.i"
	@echo "... src/network/tcp/tcp_handler.s"
	@echo "... src/util/compression_util.o"
	@echo "... src/util/compression_util.i"
	@echo "... src/util/compression_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/drs239/Git-Projs/Minecraft_Cpp/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

